export const EVENT_LABELS: Record<string, string> = {
  AccessCorridorBridge: "完成靠接",
  AccessCorridorBridgeBegin: "靠桥开始",
  AircraftBeginsTaxi: "开始滑行",
  AircraftEntry: "飞机入位",
  AircraftLeave: "飞机推出",
  AircraftStart: "飞机开始入位",
  BaggageTractorDeparted: "货邮行李车离位",
  BaggageTractorInPosition: "货邮行李车就位",
  CloseCabinDoor: "关客舱门",
  CloseCargoDoor: "关货舱门",
  FirstPieceBaggage: "首件行李到达",
  FlightFoodArrival: "配餐车到位",
  FlightFoodEnd: "完成配餐",
  FlightFoodLeave: "配餐车离位",
  FlightFoodStart: "开始配餐",
  GuideCarEnd: "引导车结束",
  GuideCarStart: "引导车开始",
  GUIDE_ONLY: "只有引导车节点",
  LadderCarEntry: "客梯车到位",
  LadderCarLeave: "客梯车离位",
  LadderCarNear: "客梯车靠近",
  LadderCarStartLeave: "客梯车开始撤离",
  LuggageCarBegin: "行李装卸开始",
  LuggageCarEnd: "行李装卸结束",
  OilseedsCarArrival: "加油车到位",
  OilseedsCarLeave: "加油车离位",
  OilseedsEnd: "完成加油",
  OilseedsStart: "开始加油",
  OpenCabinDoor: "开客舱门",
  OpenCargoDoor: "开货舱门",
  PlaceChockBegin: "放轮挡开始",
  PlaceChockEnd: "放轮挡完成",
  ReflectiveBucketPlacementCompletion: "反光锥放置完成",
  ReflectiveBucketPlacementStart: "反光锥放置开始",
  RemoveCorridorBridge: "撤廊桥结束",
  RemoveCorridorBridgeBegin: "撤廊桥开始",
  RemoveWheelGearEnd: "撤轮挡完成",
  RemoveWheelGearStart: "撤轮挡开始",
  TowArrival: "牵引车就位",
  TowEnd: "牵引车结束",
  TowShow: "牵引车出现",
  TractorInPosition: "牵引车到位"
};

export function eventLabel(eventType: string): string {
  return EVENT_LABELS[eventType] || "未命名节点";
}
